;
[Common_Ch]
LicenseText="本软件使用了Qt库进行开发，并且所使用的Qt库是基于LGPLv2.1进行许可的。具体的源码获得位置和许可证的内容见下边的列表。"
SrcText="<a href=%1>获得本产品所使用的Qt库的源代码位置请点击此处</a>"
GPLText="<a href=%1>阅读GPLv3许可内容</a>"
LGPLText="<a href=%1>阅读LGPLv2.1许可内容</a>"
Title="关于Qt"

[Common_En]
LicenseText="This product is dynamicly linked with Qt Library,which is licensed by LGPLv2.1.To get source code of Qt library used in this product or to view details of GPLv3/LGPLv2.1 license, please click the link listed as below."
SrcText="<a href=%1>View source code of Qt used in this product</a>"
GPLText="<a href=%1>View clause of GPLv3 </a>"
LGPLText="<a href=%1>View clause of LGPLv2.1</a>"
Title="About Qt"

[5.9.9]
URL="https://github.com/GlodonOpenSrc/Qt5.9.9_Glodon"

[5.6.3]
URL="https://github.com/GlodonOpenSrc/Qt5.6.3_Glodon"

[5.5.1]
URL="https://github.com/GlodonOpenSrc/Qt5.5.1_Glodon"

[4.8.5]
URL="https://github.com/GlodonOpenSrc/Qt4.8.5_Glodon"

[5.6.7]
URL="https://github.com/GlodonOpenSrc/Qt5.6.7_Glodon"

[5.14.2]
URL="https://github.com/GlodonOpenSrc/Qt5.14.2_Glodon"

[5.15.2]
URL="https://github.com/GlodonOpenSrc/Qt5.15.2_Glodon"

[5.9.5]
URL="https://github.com/GlodonOpenSrc/Qt5.9.5_Glodon"

[5.4.2]
URL="https://github.com/GlodonOpenSrc/Qt5.4.2_Glodon"

[5.9.0]
URL="https://github.com/GlodonOpenSrc/Qt5.9.0_Glodon"